# config for the power strip
- Power_Strip_Count: 1
- default_Name: power_strip
- default_Start_Id: 101
- default_Mask: 24
- default_IP: 192.168.1.20
- default_Username: ubnt
- default_Password: ubnt
- default_Ports: 6